index:
    path: /
    controller: App\Controller\HomeController:index
app_logout:
    path: /logout
    controller: App\Controller\HomeController::index
app_login:
    path: /login
    controller: App\Controller\SecurityController::login
